export const lineChartOptions = {
   labels: "",
   graphData: [],
   chartTitle: "",
   isLegendVisible: false,
   stepSize: "",
   isGridDotted: false,
   isXAxisGridVisible: false,
   isYAxisGridVisible: false,
   isXAxisVisible: true,
   isYAxisVisible: true,
   xAxisTitleVisible: false,
   yAxisTitleVisible: false,
   xAxisTitleText: "",
   yAxisTitleText: "",
   legendPos: "top",
};
